### ISSUE TITLE
Getting a weird error when trying to run changelogs

### ISSUE THREAD

**Issue by anacierdem** [semantic-release/changelog#262]
See [here](https://github.com/anacierdem/libdragon-docker/actions/runs/3112843634/jobs/5046728745) for a reference workflow.

```
[12:47:03 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
    at new NodeError (internal/errors.js:322:7)
    at PassThrough.Writable.write (internal/streams/writable.js:285:13)
    at Transform.ondata (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Transform.emit (events.js:400:28)
    at addChunk (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Transform.Readable.push (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Transform.push (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Transform._flush (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/conventional-changelog-writer/index.js:156:14)
    at Transform.prefinish (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:[129](https://github.com/anacierdem/libdragon-docker/actions/runs/3112843634/jobs/5046728745#step:5:130):10) {
  code: 'ERR_INVALID_ARG_TYPE',
  bufferedData: '',
  pluginName: '@semantic-release/release-notes-generator'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
    at new NodeError (internal/errors.js:322:7)
    at PassThrough.Writable.write (internal/streams/writable.js:285:13)
    at Transform.ondata (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Transform.emit (events.js:400:28)
    at addChunk (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Transform.Readable.push (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Transform.push (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Transform._flush (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/conventional-changelog-writer/index.js:156:14)
    at Transform.prefinish (/home/runner/work/libdragon-docker/libdragon-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:129:10) {
  code: 'ERR_INVALID_ARG_TYPE',
  bufferedData: '',
  pluginName: '@semantic-release/release-notes-generator'
}
```

It seem to try to push an Object to a `through` instance but how is it possible for this to work at all then?

This potentially relates to `conventional-changelog-writer` but wanted to make sure if there is anything known when used with `semantic-release/changelog` as it is using this library as a major dependency.

**Comment by anacierdem** [comment]
Wrong repository...
