### ISSUE TITLE
Unable to run plugin on prepare hook

### ISSUE THREAD

**Issue by adrigzr** [semantic-release/changelog#32]
Hi, 

Node: v10.0.0

Default configuration:

```
{
    "prepare": [
        "@semantic-release/changelog",
        "@semantic-release/npm",
        "@semantic-release/git"
    ],
    "verifyConditions": [
        "@semantic-release/changelog",
        "@semantic-release/npm",
        "@semantic-release/git",
        "@semantic-release/github"
    ]
}
```

Error:

```
[Semantic release]: An error occurred while running semantic-release: { TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1090:7)
    at module.exports (.../node_modules/@semantic-release/changelog/lib/prepare.js:7:30)
    at prepare (.../node_modules/@semantic-release/changelog/index.js:25:9)
    at validator (.../node_modules/semantic-release/lib/plugins/normalize.js:46:28)
    at pReduce (.../node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (.../node_modules/p-reduce/index.js:16:10)
```

Seems to be related to missing `cwd` property on `context` argument.

**Comment by adrigzr** [comment]
Didn't see breaking change of last commit.
