### ISSUE TITLE
Changelog not created in repo

### ISSUE THREAD

**Issue by binhxn** [semantic-release/changelog#74]
I apologize for the repetitive post of a very similar issue, but the solutions provided doesn't solve my case.  I'm using CircleCI to run my builds and I'm getting a type error specifically at `@semantic-release/git` **prepare** step:
```
[6:32:47 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Cannot read property 'name' of undefined
    at module.exports (/home/circleci/repo/node_modules/@semantic-release/git/lib/prepare.js:69:38)
    at processTicksAndRejections (internal/process/task_queues.js:86:5) pluginName: '@semantic-release/git' }
```

Here are my dependencies:
```json
"@semantic-release/changelog": "^3.0.6",
"@semantic-release/git": "^8.0.0",
"semantic-release": "^15.13.30",
"semantic-release-gitmoji": "^1.3.2"
```

Here are my configs:
```
module.exports = {
  plugins: [
    [
      'semantic-release-gitmoji',
      {
        releaseRules: {
          major: [':boom:'],
          minor: [':sparkles:'],
          patch: [':bug:', ':ambulance:', ':lock:'],
        },
      },
    ],
    '@semantic-release/changelog',
    '@semantic-release/github',
    '@semantic-release/git',
  ],
};

```

**Note**: I'm using `semantic-release-gitmoji`, which uses both `@semantic-release/commit-analyzer` and `@semantic-release/release-notes-generator` by default.

I've followed the examples provided in the docs and even tried different configuration options of `@semantic-release/changelog` and `@semantic-release/git`. 

I'm not sure if the **name** type error is referring to my `package.json`, but I do have it present. I'm not sure what the issue is at this point. Is there anything I'm missing? Any suggestions/solutions would be grateful!

<details>
  <summary>Expand to see CircleCI log</summary>
  
```
#!/bin/bash -eo pipefail
yarn release
yarn run v1.15.2
$ semantic-release
[6:32:46 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.30
[6:32:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[6:32:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[6:32:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[6:32:46 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "semantic-release-gitmoji"
[6:32:46 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "semantic-release-gitmoji"
[6:32:46 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[6:32:46 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[6:32:46 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[6:32:46 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[6:32:46 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[6:32:46 PM] [semantic-release] › ✔  Run automated release from branch master
[6:32:47 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:32:47 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[6:32:47 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[6:32:47 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[6:32:47 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[6:32:47 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[6:32:47 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[6:32:47 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[6:32:47 PM] [semantic-release] › ℹ  Found git tag v1.5.0 associated with version 1.5.0
[6:32:47 PM] [semantic-release] › ℹ  Found 1 commits since last release
[6:32:47 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "semantic-release-gitmoji"
[6:32:47 PM] [semantic-release] [semantic-release-gitmoji] › ℹ  The next release will be a "patch" release.
[6:32:47 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "semantic-release-gitmoji"
[6:32:47 PM] [semantic-release] › ℹ  The next release version is 1.5.1
[6:32:47 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "semantic-release-gitmoji"
[6:32:47 PM] [semantic-release] [semantic-release-gitmoji] › ℹ  Release notes are generated.
[6:32:47 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "semantic-release-gitmoji"
[6:32:47 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[6:32:47 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Create /home/circleci/repo/CHANGELOG.md
[6:32:47 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[6:32:47 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[6:32:47 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
[6:32:47 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/git"
[6:32:47 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Cannot read property 'name' of undefined
    at module.exports (/home/circleci/repo/node_modules/@semantic-release/git/lib/prepare.js:69:38)
    at processTicksAndRejections (internal/process/task_queues.js:86:5) pluginName: '@semantic-release/git' }
{ TypeError: Cannot read property 'name' of undefined
    at module.exports (/home/circleci/repo/node_modules/@semantic-release/git/lib/prepare.js:69:38)
    at processTicksAndRejections (internal/process/task_queues.js:86:5) pluginName: '@semantic-release/git' }error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
```
</details>

**Comment by pvdlg** [comment]
the error happens because you are running a version of `@semantic-release/git` made for semantic-release@16.0.0 and run version 15.13.30.

There is a [`peerDependencies` definition in `@semantic-release/git`](https://github.com/semantic-release/git/blob/master/package.json#L78) that should have gave you a warning during the install.

**Comment by binhxn** [comment]
That worked, thanks for your help!
